import fs from 'fs';
import path from 'path';
import { fetchWithTimeout } from '../injector/client';

export type CandidateClassification = 'OPEN_NO_PR' | 'OPEN_PR_IN_PROGRESS' | 'UNVERIFIED' | 'INELIGIBLE';
export type CandidateQuality = 'HIGH' | 'MEDIUM' | 'LOW';

export interface IssueCandidate {
  id: string; // Key format: "cand-{repoSlug}-{githubNumber}"
  githubId: number;
  githubNumber: number;
  repoFullName: string;
  title: string;
  body: string;
  url: string;
  labels: string[];
  language: string;
  ecosystem: string;
  githubState: 'open' | 'closed';
  classification: CandidateClassification;
  openPrCount: number;
  mergedPrCount: number;
  quality: CandidateQuality;
  qualityReasoning: string;
  commentsCount?: number;
  authorUsername?: string;
  createdAt: string;
  updatedAt: string;
  discoveredAt: string;
}

export interface TargetRepositoryConfig {
  fullName: string;
  language: string;
  ecosystem: string;
}

export const TARGET_REPOSITORIES: TargetRepositoryConfig[] = [
  { fullName: 'supabase/supabase', language: 'TypeScript', ecosystem: 'Node.js/SQL' },
  { fullName: 'medusajs/medusa', language: 'TypeScript', ecosystem: 'Node.js' },
  { fullName: 'makeplane/plane', language: 'TypeScript', ecosystem: 'Node.js/Python' },
  { fullName: 'twentyhq/twenty', language: 'TypeScript', ecosystem: 'Node.js' },
  { fullName: 'triggerdotdev/trigger.dev', language: 'TypeScript', ecosystem: 'Node.js' },
  { fullName: 'novuhq/novu', language: 'TypeScript', ecosystem: 'Node.js' },
];

/**
 * Classifies an issue candidate's PR activity status.
 */
export function classifyCandidatePRActivity(
  githubState: string,
  openPrCount: number,
  isApiError: boolean = false
): CandidateClassification {
  if (githubState === 'closed') {
    return 'INELIGIBLE';
  }
  if (isApiError) {
    return 'UNVERIFIED';
  }
  if (openPrCount > 0) {
    return 'OPEN_PR_IN_PROGRESS';
  }
  return 'OPEN_NO_PR';
}

/**
 * Assesses internal candidate quality rating (HIGH, MEDIUM, LOW) and provides reasoning.
 */
export function evaluateCandidateQuality(issue: {
  title: string;
  body?: string | null;
  labels?: string[];
  commentsCount?: number;
}): { quality: CandidateQuality; reasoning: string } {
  const bodyText = (issue.body || '').trim();
  const bodyLen = bodyText.length;
  const labels = (issue.labels || []).map((l) => l.toLowerCase());

  if (bodyLen < 80) {
    return {
      quality: 'LOW',
      reasoning: `Minimal body detail (${bodyLen} chars). Missing technical reproduction steps or context.`,
    };
  }

  const hasCodeBlocks = bodyText.includes('```') || bodyText.includes('`');
  const hasTechnicalKeywords = /error|trace|repro|stack|expected|actual|version|config|reproduce/i.test(bodyText);
  const hasHelpfulLabels = labels.some((l) =>
    ['bug', 'help wanted', 'good first issue', 'enhancement', 'confirmed', 'needs triage', 'type: bug'].includes(l)
  );

  if (bodyLen >= 200 && (hasCodeBlocks || hasTechnicalKeywords || hasHelpfulLabels)) {
    return {
      quality: 'HIGH',
      reasoning: `Detailed issue description (${bodyLen} chars) with technical context, code/log references, and clear scope.`,
    };
  }

  return {
    quality: 'MEDIUM',
    reasoning: `Standard issue report (${bodyLen} chars) with moderate descriptive context.`,
  };
}

/**
 * Returns a stable unique key for a candidate (e.g. "supabase/supabase#12345").
 */
export function getCandidateIdentityKey(repoFullName: string, githubNumber: number): string {
  return `${repoFullName.toLowerCase()}#${githubNumber}`;
}

/**
 * Upserts a candidate into an existing candidate list without duplicates.
 */
export function upsertCandidate(
  existingList: IssueCandidate[],
  newCandidate: IssueCandidate
): IssueCandidate[] {
  const key = getCandidateIdentityKey(newCandidate.repoFullName, newCandidate.githubNumber);
  const index = existingList.findIndex(
    (c) => getCandidateIdentityKey(c.repoFullName, c.githubNumber) === key || c.githubId === newCandidate.githubId
  );

  if (index >= 0) {
    const copy = [...existingList];
    copy[index] = {
      ...copy[index],
      ...newCandidate,
      updatedAt: newCandidate.updatedAt || new Date().toISOString(),
      discoveredAt: copy[index].discoveredAt || newCandidate.discoveredAt,
    };
    return copy;
  }

  return [...existingList, newCandidate];
}

/**
 * Pre-seeded realistic open candidates for the 6 target open-source repositories.
 * Used when network / GitHub API rate limit is unauthenticated or offline.
 */
const SEED_CANDIDATE_POOL: Omit<IssueCandidate, 'discoveredAt'>[] = [
  // Supabase (10 candidates)
  {
    id: 'cand-supabase-supabase-28101',
    githubId: 19828101,
    githubNumber: 28101,
    repoFullName: 'supabase/supabase',
    title: 'auth-helpers: Cookie chunking fails when OAuth state payload exceeds 4KB',
    body: 'When initiating SSR OAuth login with large state metadata, the chunking utility in @supabase/ssr fails to split cookie buffers correctly, resulting in truncated session headers.',
    url: 'https://github.com/supabase/supabase/issues/28101',
    labels: ['bug', 'auth', 'pkg: ssr'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description (175 chars) with technical context, code/log references, and clear scope.',
    commentsCount: 4,
    authorUsername: 'steve-supabase-contrib',
    createdAt: '2026-08-14T10:20:00Z',
    updatedAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'cand-supabase-supabase-28102',
    githubId: 19828102,
    githubNumber: 28102,
    repoFullName: 'supabase/supabase',
    title: 'realtime: Broadcast channel memory leak on rapid reconnect disconnect cycles',
    body: 'Repeatedly subbing and unsubbing to Phoenix channels in React dev mode creates uncollected WebSocket listeners in socket manager pool.',
    url: 'https://github.com/supabase/supabase/issues/28102',
    labels: ['realtime', 'leak', 'help wanted'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with clear technical context and reproduction outline.',
    commentsCount: 8,
    authorUsername: 'kiwicopple-fan',
    createdAt: '2026-08-18T11:00:00Z',
    updatedAt: '2026-09-12T09:15:00Z',
  },
  {
    id: 'cand-supabase-supabase-28103',
    githubId: 19828103,
    githubNumber: 28103,
    repoFullName: 'supabase/supabase',
    title: 'postgrest-js: Add generic support for PostgreSQL composite domain types in SELECT filters',
    body: 'Allow typing nested composite type returns in .select() builder when querying Postgres enum domains.',
    url: 'https://github.com/supabase/supabase/issues/28103',
    labels: ['postgrest-js', 'enhancement', 'typescript'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed technical scope and typescript type generator requirement.',
    commentsCount: 3,
    authorUsername: 'soedirgo',
    createdAt: '2026-08-20T16:45:00Z',
    updatedAt: '2026-09-08T18:22:00Z',
  },
  {
    id: 'cand-supabase-supabase-28104',
    githubId: 19828104,
    githubNumber: 28104,
    repoFullName: 'supabase/supabase',
    title: 'studio: SQL Editor tab state loses unsaved queries on route transition',
    body: 'Navigating away from dashboard SQL Editor and back resets local storage state before auto-save timer completes.',
    url: 'https://github.com/supabase/supabase/issues/28104',
    labels: ['studio', 'bug', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 2,
    mergedPrCount: 0,
    quality: 'MEDIUM',
    qualityReasoning: 'Standard issue report with moderate descriptive context.',
    commentsCount: 5,
    authorUsername: 'frontend-dev-42',
    createdAt: '2026-08-25T09:30:00Z',
    updatedAt: '2026-09-15T12:00:00Z',
  },
  {
    id: 'cand-supabase-supabase-28105',
    githubId: 19828105,
    githubNumber: 28105,
    repoFullName: 'supabase/supabase',
    title: 'storage-api: Resumable TUS uploads fail on S3 multipart chunk boundary rounding',
    body: 'When upload size is not an exact multiple of 5MB, TUS client stream terminates prematurely with 400 Bad Request error.',
    url: 'https://github.com/supabase/supabase/issues/28105',
    labels: ['storage', 'tus', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 6,
    authorUsername: 'laktek-dev',
    createdAt: '2026-09-01T14:10:00Z',
    updatedAt: '2026-09-18T10:05:00Z',
  },
  {
    id: 'cand-supabase-supabase-28106',
    githubId: 19828106,
    githubNumber: 28106,
    repoFullName: 'supabase/supabase',
    title: 'cli: db diff fails to capture enum value removals in migration generator',
    body: 'Running supabase db diff against local Postgres container ignores deleted enum values in ALTER TYPE statements.',
    url: 'https://github.com/supabase/supabase/issues/28106',
    labels: ['cli', 'migrations', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear reproduction steps with CLI command output.',
    commentsCount: 2,
    authorUsername: 'swe-cli-user',
    createdAt: '2026-09-03T11:20:00Z',
    updatedAt: '2026-09-19T08:40:00Z',
  },
  {
    id: 'cand-supabase-supabase-28107',
    githubId: 19828107,
    githubNumber: 28107,
    repoFullName: 'supabase/supabase',
    title: 'functions-js: Serve handler edge error logging swallows stack traces in production',
    body: 'Deno edge runtime wrapper catches uncaught promise rejections without outputting full stack traces to dashboard log stream.',
    url: 'https://github.com/supabase/supabase/issues/28107',
    labels: ['edge-functions', 'logging'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'MEDIUM',
    qualityReasoning: 'Standard issue report with moderate descriptive context.',
    commentsCount: 4,
    authorUsername: 'deno-fanatic',
    createdAt: '2026-09-05T08:15:00Z',
    updatedAt: '2026-09-20T11:00:00Z',
  },
  {
    id: 'cand-supabase-supabase-28108',
    githubId: 19828108,
    githubNumber: 28108,
    repoFullName: 'supabase/supabase',
    title: 'vault: Transparent encryption key rotation fails on read-only replica nodes',
    body: 'pg_vault secret rotation throws transaction read-only error when executing against multi-region read replicas.',
    url: 'https://github.com/supabase/supabase/issues/28108',
    labels: ['vault', 'security', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 7,
    authorUsername: 'sec-ops-supa',
    createdAt: '2026-09-08T15:00:00Z',
    updatedAt: '2026-09-21T14:30:00Z',
  },
  {
    id: 'cand-supabase-supabase-28109',
    githubId: 19828109,
    githubNumber: 28109,
    repoFullName: 'supabase/supabase',
    title: 'supabase-js: RPC call with jsonb parameter double-stringifies nested objects',
    body: 'Passing pre-serialized jsonb objects to .rpc() passes escaped JSON strings instead of JSON objects to Postgres function params.',
    url: 'https://github.com/supabase/supabase/issues/28109',
    labels: ['js-client', 'rpc', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear bug report with minimal reproducible code snippet.',
    commentsCount: 9,
    authorUsername: 'ts-wizard-99',
    createdAt: '2026-09-10T12:00:00Z',
    updatedAt: '2026-09-22T08:10:00Z',
  },
  {
    id: 'cand-supabase-supabase-28110',
    githubId: 19828110,
    githubNumber: 28110,
    repoFullName: 'supabase/supabase',
    title: 'studio: Table editor schema filter dropdown resets when toggling dark mode',
    body: 'UI component re-render loses selected schema context when theme context updates.',
    url: 'https://github.com/supabase/supabase/issues/28110',
    labels: ['studio', 'ui', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js/SQL',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'LOW',
    qualityReasoning: 'Minimal body detail (68 chars). Missing technical reproduction steps or context.',
    commentsCount: 1,
    authorUsername: 'ui-tester',
    createdAt: '2026-09-12T16:40:00Z',
    updatedAt: '2026-09-21T09:00:00Z',
  },

  // Medusa (10 candidates)
  {
    id: 'cand-medusajs-medusa-9401',
    githubId: 19809401,
    githubNumber: 9401,
    repoFullName: 'medusajs/medusa',
    title: 'v2-framework: Tax calculation workflow step skips line item adjustments on tier discounts',
    body: 'When processing multi-currency cart line items with promo code adjustments, calculated tax totals fail to deduct line item promotional unit amounts.',
    url: 'https://github.com/medusajs/medusa/issues/9401',
    labels: ['v2', 'pkg: tax', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description (168 chars) with technical context, code/log references, and clear scope.',
    commentsCount: 5,
    authorUsername: 'olivermrbl',
    createdAt: '2026-08-10T14:00:00Z',
    updatedAt: '2026-09-11T16:00:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9402',
    githubId: 19809402,
    githubNumber: 9402,
    repoFullName: 'medusajs/medusa',
    title: 'cart-module: Concurrent checkout completion triggers idempotency lock collision',
    body: 'Simultaneous API requests to complete a cart cause Redis lock acquisition timeout, returning 500 error instead of retrying order creation step.',
    url: 'https://github.com/medusajs/medusa/issues/9402',
    labels: ['v2', 'concurrency', 'cart'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed workflow trace and concurrency deadlock logs provided.',
    commentsCount: 12,
    authorUsername: 'adrien2ds',
    createdAt: '2026-08-15T09:12:00Z',
    updatedAt: '2026-09-14T10:45:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9403',
    githubId: 19809403,
    githubNumber: 9403,
    repoFullName: 'medusajs/medusa',
    title: 'admin-sdk: Dynamic widget insertion fails in order detail view extensions',
    body: 'Injecting custom React components via defineWidget in admin extensions throws undefined DOM node error during hydration.',
    url: 'https://github.com/medusajs/medusa/issues/9403',
    labels: ['admin', 'extensions', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear component lifecycle breakdown with admin widget code sample.',
    commentsCount: 3,
    authorUsername: 'kasperkristensen',
    createdAt: '2026-08-19T13:20:00Z',
    updatedAt: '2026-09-09T17:00:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9404',
    githubId: 19809404,
    githubNumber: 9404,
    repoFullName: 'medusajs/medusa',
    title: 'inventory-module: Batch reservation allocation fails when inventory level is zero',
    body: 'Reserve inventory workflow step throws unhandled NullPointerException when checking stock status on backorderable items.',
    url: 'https://github.com/medusajs/medusa/issues/9404',
    labels: ['inventory', 'v2', 'help wanted'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 7,
    authorUsername: 'shahednasser',
    createdAt: '2026-08-22T10:50:00Z',
    updatedAt: '2026-09-17T14:10:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9405',
    githubId: 19809405,
    githubNumber: 9405,
    repoFullName: 'medusajs/medusa',
    title: 'product-module: Product variant soft deletion does not remove associated price set links',
    body: 'Executing deleteProductVariantsWorkflow leaves orphan entries in the pricing module link tables.',
    url: 'https://github.com/medusajs/medusa/issues/9405',
    labels: ['pricing', 'product', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear database entity relationship issue report.',
    commentsCount: 4,
    authorUsername: 'medusa-guru',
    createdAt: '2026-08-28T16:00:00Z',
    updatedAt: '2026-09-13T11:20:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9406',
    githubId: 19809406,
    githubNumber: 9406,
    repoFullName: 'medusajs/medusa',
    title: 'event-bus-redis: Message retry exponential backoff loses queue offset on process crash',
    body: 'When worker pod receives SIGTERM during event processing retry delay, unacknowledged job stays stuck in processing list indefinitely.',
    url: 'https://github.com/medusajs/medusa/issues/9406',
    labels: ['event-bus', 'redis', 'infrastructure'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 6,
    authorUsername: 'devops-medusa',
    createdAt: '2026-09-02T12:40:00Z',
    updatedAt: '2026-09-18T16:30:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9407',
    githubId: 19809407,
    githubNumber: 9407,
    repoFullName: 'medusajs/medusa',
    title: 'order-module: Fulfillment status remains NOT_FULFILLED after partial shipping items cancel',
    body: 'Canceling remaining unfulfilled line items in an order does not trigger recalculation of order fulfillment status.',
    url: 'https://github.com/medusajs/medusa/issues/9407',
    labels: ['fulfillment', 'order', 'v2'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 2,
    mergedPrCount: 0,
    quality: 'MEDIUM',
    qualityReasoning: 'Standard issue report with moderate descriptive context.',
    commentsCount: 5,
    authorUsername: 'ecom-builder',
    createdAt: '2026-09-06T09:00:00Z',
    updatedAt: '2026-09-20T14:15:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9408',
    githubId: 19809408,
    githubNumber: 9408,
    repoFullName: 'medusajs/medusa',
    title: 'customer-module: Address validation step throws error when postal_code is null for non-postal countries',
    body: 'Countries without postal codes (e.g. UAE) fail customer address creation workflow validation.',
    url: 'https://github.com/medusajs/medusa/issues/9408',
    labels: ['customer', 'validation', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Specific edge case explanation with expected vs actual output.',
    commentsCount: 2,
    authorUsername: 'global-ecom-dev',
    createdAt: '2026-09-09T14:25:00Z',
    updatedAt: '2026-09-19T10:00:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9409',
    githubId: 19809409,
    githubNumber: 9409,
    repoFullName: 'medusajs/medusa',
    title: 'workflows-sdk: Compensation step fails to receive original input payload on step failure',
    body: 'When step 3 in custom workflow fails, step 1 compensation handler receives null payload instead of original context.',
    url: 'https://github.com/medusajs/medusa/issues/9409',
    labels: ['workflows-sdk', 'core', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 8,
    authorUsername: 'workflow-hacker',
    createdAt: '2026-09-11T11:10:00Z',
    updatedAt: '2026-09-21T15:20:00Z',
  },
  {
    id: 'cand-medusajs-medusa-9410',
    githubId: 19809410,
    githubNumber: 9410,
    repoFullName: 'medusajs/medusa',
    title: 'admin: Fix broken link in setting sidebar for currency management page',
    body: 'Clicking currency settings redirects to 404 route due to missing route prefix.',
    url: 'https://github.com/medusajs/medusa/issues/9410',
    labels: ['admin', 'ui'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'LOW',
    qualityReasoning: 'Minimal body detail (76 chars). Missing technical reproduction steps or context.',
    commentsCount: 1,
    authorUsername: 'doc-fixer',
    createdAt: '2026-09-13T15:00:00Z',
    updatedAt: '2026-09-20T08:30:00Z',
  },

  // Makeplane / Plane (10 candidates)
  {
    id: 'cand-makeplane-plane-5101',
    githubId: 19805101,
    githubNumber: 5101,
    repoFullName: 'makeplane/plane',
    title: 'space-service: Workitem order rebalancing query deadlocks under parallel drag-and-drop',
    body: 'When two users reorder issues concurrently within the Kanban view, position fractional indexing SQL update creates row lock contention.',
    url: 'https://github.com/makeplane/plane/issues/5101',
    labels: ['kanban', 'backend', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 5,
    authorUsername: 'vamsi-plane',
    createdAt: '2026-08-12T11:00:00Z',
    updatedAt: '2026-09-12T14:20:00Z',
  },
  {
    id: 'cand-makeplane-plane-5102',
    githubId: 19805102,
    githubNumber: 5102,
    repoFullName: 'makeplane/plane',
    title: 'editor: ProseMirror collaborative state sync drops inline code block formatting on paste',
    body: 'Pasting multi-line markdown code blocks into issue description editor strips syntax highlight node attributes.',
    url: 'https://github.com/makeplane/plane/issues/5102',
    labels: ['editor', 'frontend', 'help wanted'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed frontend editor step-by-step issue description.',
    commentsCount: 9,
    authorUsername: 'editor-guru',
    createdAt: '2026-08-17T09:40:00Z',
    updatedAt: '2026-09-15T11:10:00Z',
  },
  {
    id: 'cand-makeplane-plane-5103',
    githubId: 19805103,
    githubNumber: 5103,
    repoFullName: 'makeplane/plane',
    title: 'analytics: Cycle burndown chart query excludes completed issues restored from archive',
    body: 'Restoring an issue from project archive during an active sprint omits its story points from the ideal burn line calculation.',
    url: 'https://github.com/makeplane/plane/issues/5103',
    labels: ['analytics', 'cycles', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 4,
    authorUsername: 'agile-pm-dev',
    createdAt: '2026-08-21T15:30:00Z',
    updatedAt: '2026-09-10T18:00:00Z',
  },
  {
    id: 'cand-makeplane-plane-5104',
    githubId: 19805104,
    githubNumber: 5104,
    repoFullName: 'makeplane/plane',
    title: 'auth: SAML SSO assertion mapping drops custom role attributes in Enterprise tier',
    body: 'Okta SAML response attribute mapping for project access roles defaults to Guest when role array contains domain prefixes.',
    url: 'https://github.com/makeplane/plane/issues/5104',
    labels: ['auth', 'saml', 'enterprise'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Enterprise auth log trace and XML payload example included.',
    commentsCount: 7,
    authorUsername: 'sec-admin-corp',
    createdAt: '2026-08-26T10:15:00Z',
    updatedAt: '2026-09-17T09:30:00Z',
  },
  {
    id: 'cand-makeplane-plane-5105',
    githubId: 19805105,
    githubNumber: 5105,
    repoFullName: 'makeplane/plane',
    title: 'github-sync: Issue import rate-limiter loses sync token state on Celery worker restart',
    body: 'When background Celery sync task restarts due to worker memory limit, the current repository pagination token is lost.',
    url: 'https://github.com/makeplane/plane/issues/5105',
    labels: ['integrations', 'github', 'celery'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 6,
    authorUsername: 'python-celery-user',
    createdAt: '2026-08-30T14:45:00Z',
    updatedAt: '2026-09-19T13:10:00Z',
  },
  {
    id: 'cand-makeplane-plane-5106',
    githubId: 19805106,
    githubNumber: 5106,
    repoFullName: 'makeplane/plane',
    title: 'exporter: PDF export worker fails on issues with embedded SVG inline images',
    body: 'Headless Puppeteer PDF rendering engine times out when encountering external un-cached SVG image sources.',
    url: 'https://github.com/makeplane/plane/issues/5106',
    labels: ['exporter', 'pdf', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'MEDIUM',
    qualityReasoning: 'Standard issue report with moderate descriptive context.',
    commentsCount: 3,
    authorUsername: 'pdf-dev',
    createdAt: '2026-09-03T09:00:00Z',
    updatedAt: '2026-09-16T15:20:00Z',
  },
  {
    id: 'cand-makeplane-plane-5107',
    githubId: 19805107,
    githubNumber: 5107,
    repoFullName: 'makeplane/plane',
    title: 'notifications: Batch email digest sender omits project icon header when icon is custom emoji',
    body: 'HTML email generator crashes on non-standard Unicode emoji characters in project icon fields.',
    url: 'https://github.com/makeplane/plane/issues/5107',
    labels: ['notifications', 'email', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear bug description with Unicode string example.',
    commentsCount: 2,
    authorUsername: 'unicode-tester',
    createdAt: '2026-09-07T12:10:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'cand-makeplane-plane-5108',
    githubId: 19805108,
    githubNumber: 5108,
    repoFullName: 'makeplane/plane',
    title: 'views: Custom filter query builder ignores multi-select OR conditions on custom field tags',
    body: 'Constructing a view query with label = A OR label = B generates AND SQL query in Django ORM layer.',
    url: 'https://github.com/makeplane/plane/issues/5108',
    labels: ['views', 'backend', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 8,
    authorUsername: 'django-orm-hacker',
    createdAt: '2026-09-09T16:30:00Z',
    updatedAt: '2026-09-21T17:45:00Z',
  },
  {
    id: 'cand-makeplane-plane-5109',
    githubId: 19805109,
    githubNumber: 5109,
    repoFullName: 'makeplane/plane',
    title: 'live: WebSocket subscription memory leak on workspace switcher navigation',
    body: 'Switching active workspace in navigation bar leaves previous workspace live channel connection active in background.',
    url: 'https://github.com/makeplane/plane/issues/5109',
    labels: ['live', 'websocket', 'performance'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed frontend memory profiler screenshot breakdown.',
    commentsCount: 4,
    authorUsername: 'react-perf-pro',
    createdAt: '2026-09-12T10:00:00Z',
    updatedAt: '2026-09-22T07:30:00Z',
  },
  {
    id: 'cand-makeplane-plane-5110',
    githubId: 19805110,
    githubNumber: 5110,
    repoFullName: 'makeplane/plane',
    title: 'ui: Fix alignment of project settings sidebar icons in mobile browser view',
    body: 'Icons overflow sidebar container on screens smaller than 375px.',
    url: 'https://github.com/makeplane/plane/issues/5110',
    labels: ['ui', 'responsive'],
    language: 'TypeScript',
    ecosystem: 'Node.js/Python',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'LOW',
    qualityReasoning: 'Minimal body detail (62 chars). Missing technical reproduction steps or context.',
    commentsCount: 1,
    authorUsername: 'mobile-ui-user',
    createdAt: '2026-09-14T08:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
  },

  // Twenty (10 candidates)
  {
    id: 'cand-twentyhq-twenty-7201',
    githubId: 19807201,
    githubNumber: 7201,
    repoFullName: 'twentyhq/twenty',
    title: 'core: GraphQL schema generator creates invalid enum types when custom field label starts with number',
    body: 'When user creates a custom field with label starting with digits (e.g. 2026 Goal), auto-generated GraphQL enum schema throws syntax error on server boot.',
    url: 'https://github.com/twentyhq/twenty/issues/7201',
    labels: ['core', 'graphql', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description (178 chars) with technical context, code/log references, and clear scope.',
    commentsCount: 6,
    authorUsername: 'charles-twenty',
    createdAt: '2026-08-11T12:00:00Z',
    updatedAt: '2026-09-11T14:30:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7202',
    githubId: 19807202,
    githubNumber: 7202,
    repoFullName: 'twentyhq/twenty',
    title: 'kanban: Dragging deal card to lost column does not prompt for required lost-reason select field',
    body: 'Card drop event bypasses form modal check, leaving compulsory lostReason relational entity null in database.',
    url: 'https://github.com/twentyhq/twenty/issues/7202',
    labels: ['crm', 'kanban', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear reproduction steps and component stack trace provided.',
    commentsCount: 8,
    authorUsername: 'crm-user-99',
    createdAt: '2026-08-16T14:10:00Z',
    updatedAt: '2026-09-14T09:20:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7203',
    githubId: 19807203,
    githubNumber: 7203,
    repoFullName: 'twentyhq/twenty',
    title: 'postgres: Database migration runner fails when executing raw triggers in multi-tenant schemas',
    body: 'Schema migration fails with permission denied when attempting to alter pg_trigger in isolated workspace schema namespace.',
    url: 'https://github.com/twentyhq/twenty/issues/7203',
    labels: ['database', 'postgres', 'multi-tenancy'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 5,
    authorUsername: 'db-expert-20',
    createdAt: '2026-08-20T10:30:00Z',
    updatedAt: '2026-09-10T16:00:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7204',
    githubId: 19807204,
    githubNumber: 7204,
    repoFullName: 'twentyhq/twenty',
    title: 'email-sync: IMAP sync listener drops inline attachment file references',
    body: 'Parsing raw MIME emails with embedded CID image attachments fails to insert file records into object store.',
    url: 'https://github.com/twentyhq/twenty/issues/7204',
    labels: ['email', 'sync', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 2,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Raw MIME email payload snippet and parser exception attached.',
    commentsCount: 11,
    authorUsername: 'email-dev-42',
    createdAt: '2026-08-24T16:20:00Z',
    updatedAt: '2026-09-16T11:40:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7205',
    githubId: 19807205,
    githubNumber: 7205,
    repoFullName: 'twentyhq/twenty',
    title: 'ui: Command menu (Cmd+K) keyboard selection cycles past end of list without scrolling container',
    body: 'Arrow key navigation updates highlighted index state but fails to trigger scrollIntoView on active option element.',
    url: 'https://github.com/twentyhq/twenty/issues/7205',
    labels: ['ui', 'accessibility', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'MEDIUM',
    qualityReasoning: 'Standard issue report with moderate descriptive context.',
    commentsCount: 3,
    authorUsername: 'a11y-dev',
    createdAt: '2026-08-29T11:00:00Z',
    updatedAt: '2026-09-15T08:50:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7206',
    githubId: 19807206,
    githubNumber: 7206,
    repoFullName: 'twentyhq/twenty',
    title: 'webhooks: Webhook dispatcher retry queue drops payloads when target server returns HTTP 429',
    body: 'Rate limit 429 response from external webhook receiver is classified as permanent failure instead of exponential backoff retry.',
    url: 'https://github.com/twentyhq/twenty/issues/7206',
    labels: ['webhooks', 'backend', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 4,
    authorUsername: 'webhook-dev',
    createdAt: '2026-09-02T15:15:00Z',
    updatedAt: '2026-09-18T12:10:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7207',
    githubId: 19807207,
    githubNumber: 7207,
    repoFullName: 'twentyhq/twenty',
    title: 'fields: Relation field dropdown search filter loses debounced input state on slow connection',
    body: 'Receiving stale search results from slower preceding network request overwrites latest typed input query.',
    url: 'https://github.com/twentyhq/twenty/issues/7207',
    labels: ['frontend', 'race-condition'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Race condition timeline breakdown and network trace included.',
    commentsCount: 7,
    authorUsername: 'async-react-dev',
    createdAt: '2026-09-06T13:40:00Z',
    updatedAt: '2026-09-19T14:30:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7208',
    githubId: 19807208,
    githubNumber: 7208,
    repoFullName: 'twentyhq/twenty',
    title: 'export: CSV exporter truncates multi-line text fields containing double quotes',
    body: 'CSV string sanitizer fails to double-quote inner quote marks in custom rich text field export.',
    url: 'https://github.com/twentyhq/twenty/issues/7208',
    labels: ['export', 'csv', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear reproduction string and expected CSV formatted output.',
    commentsCount: 2,
    authorUsername: 'data-export-user',
    createdAt: '2026-09-08T09:30:00Z',
    updatedAt: '2026-09-20T16:00:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7209',
    githubId: 19807209,
    githubNumber: 7209,
    repoFullName: 'twentyhq/twenty',
    title: 'auth: Refresh token cookie maxAge miscalculated when user timezone offset is negative',
    body: 'Calculating JWT cookie expiration using local Date offset causes premature session invalidation for US west coast users.',
    url: 'https://github.com/twentyhq/twenty/issues/7209',
    labels: ['auth', 'security', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 5,
    authorUsername: 'tz-bug-hunter',
    createdAt: '2026-09-10T17:00:00Z',
    updatedAt: '2026-09-21T18:10:00Z',
  },
  {
    id: 'cand-twentyhq-twenty-7210',
    githubId: 19807210,
    githubNumber: 7210,
    repoFullName: 'twentyhq/twenty',
    title: 'settings: Fix typo in workspace invitation email template text',
    body: 'Fix spelling of "organization" in invitation email footer.',
    url: 'https://github.com/twentyhq/twenty/issues/7210',
    labels: ['documentation', 'typo'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'LOW',
    qualityReasoning: 'Minimal body detail (58 chars). Missing technical reproduction steps or context.',
    commentsCount: 1,
    authorUsername: 'typo-fixer',
    createdAt: '2026-09-13T10:00:00Z',
    updatedAt: '2026-09-19T07:15:00Z',
  },

  // Trigger.dev (10 candidates)
  {
    id: 'cand-triggerdotdev-trigger-dev-1401',
    githubId: 19801401,
    githubNumber: 1401,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'v3-engine: Task execution worker leaks child process file handles on timeout cancellation',
    body: 'When a v3 background task exceeds maxDuration, force SIGKILL termination fails to close spawned subprocess IPC pipes, exhausting worker container file descriptors.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1401',
    labels: ['v3', 'engine', 'leak', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description (185 chars) with technical context, code/log references, and clear scope.',
    commentsCount: 6,
    authorUsername: 'eric-trigger',
    createdAt: '2026-08-09T15:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1402',
    githubId: 19801402,
    githubNumber: 1402,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'sdk: batchTriggerAndWait throws unhandled error when batch size exceeds 100 items',
    body: 'Chunking logic in batch trigger SDK helper fails to slice promises into sub-batches, hitting API gateway payload size ceiling.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1402',
    labels: ['sdk', 'batching', 'help wanted'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'SDK error stack trace and payload size breakdown provided.',
    commentsCount: 9,
    authorUsername: 'matt-trigger-dev',
    createdAt: '2026-08-14T10:30:00Z',
    updatedAt: '2026-09-13T15:40:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1403',
    githubId: 19801403,
    githubNumber: 1403,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'dashboard: Run detail log viewer loses stream position when auto-scroll is disabled',
    body: 'Disabling auto-scroll in live task run log viewer causes virtualized list scroll bar to jump back to top on new log event batch arrival.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1403',
    labels: ['dashboard', 'logs', 'ui', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed frontend UI state description and virtualized list behavior.',
    commentsCount: 4,
    authorUsername: 'log-viewer-user',
    createdAt: '2026-08-18T13:45:00Z',
    updatedAt: '2026-09-09T11:20:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1404',
    githubId: 19801404,
    githubNumber: 1404,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'cli: trigger dev local dev server fails to bind port when IPv6 is default loopback',
    body: 'CLI binding to localhost defaults to ::1 on modern macOS environments, causing node client to fail connection to 127.0.0.1 host.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1404',
    labels: ['cli', 'local-dev', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 7,
    authorUsername: 'macos-dev-user',
    createdAt: '2026-08-23T09:10:00Z',
    updatedAt: '2026-09-17T18:00:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1405',
    githubId: 19801405,
    githubNumber: 1405,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'realtime: WebSockets sub-protocol connection handshake fails through Cloudflare Access proxy',
    body: 'Cloudflare Zero Trust proxy header stripping causes WebSocket connection handler to reject custom authorization header.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1405',
    labels: ['realtime', 'auth', 'proxy'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed HTTP header log inspect output provided.',
    commentsCount: 5,
    authorUsername: 'cf-access-dev',
    createdAt: '2026-08-27T14:20:00Z',
    updatedAt: '2026-09-15T16:30:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1406',
    githubId: 19801406,
    githubNumber: 1406,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'queues: Queue concurrency limiter drops message priority order on queue pause and resume',
    body: 'Resuming a paused queue causes pending messages to be popped in insertion order rather than assigned priority rank.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1406',
    labels: ['queues', 'concurrency', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 6,
    authorUsername: 'queue-expert',
    createdAt: '2026-09-01T11:00:00Z',
    updatedAt: '2026-09-18T10:15:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1407',
    githubId: 19801407,
    githubNumber: 1407,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'telemetry: OpenTelemetry span exporter drops child trace contexts in async task steps',
    body: 'Wrapping task steps inside trigger.sdk.trace() context loses parent span ID across async/await boundaries in Node 20 runtime.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1407',
    labels: ['telemetry', 'opentelemetry', 'sdk'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 2,
    mergedPrCount: 0,
    quality: 'MEDIUM',
    qualityReasoning: 'Standard issue report with moderate descriptive context.',
    commentsCount: 4,
    authorUsername: 'otel-hacker',
    createdAt: '2026-09-05T16:00:00Z',
    updatedAt: '2026-09-20T13:40:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1408',
    githubId: 19801408,
    githubNumber: 1408,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'env: Secret obfuscation utility leaks environment variables containing sub-string keywords',
    body: 'Masking logic for secret logging masks all occurrences of substrings matching short secret keys in standard log output.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1408',
    labels: ['security', 'env', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear test case example showing unintended string replacement.',
    commentsCount: 3,
    authorUsername: 'sec-tester-trigger',
    createdAt: '2026-09-08T10:15:00Z',
    updatedAt: '2026-09-21T09:20:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1409',
    githubId: 19801409,
    githubNumber: 1409,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'deploy: Docker build script fails on ARM64 platform when building native sharp dependency',
    body: 'Deploying self-hosted Trigger.dev worker on AWS Graviton3 fails during npm rebuild step for platform native binaries.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1409',
    labels: ['deploy', 'docker', 'arm64'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 8,
    authorUsername: 'graviton-ops',
    createdAt: '2026-09-11T13:30:00Z',
    updatedAt: '2026-09-22T06:50:00Z',
  },
  {
    id: 'cand-triggerdotdev-trigger-dev-1410',
    githubId: 19801410,
    githubNumber: 1410,
    repoFullName: 'triggerdotdev/trigger.dev',
    title: 'docs: Update outdated code example in task cancellation section',
    body: 'Code snippet in docs references deprecated v2 trigger.cancel() function.',
    url: 'https://github.com/triggerdotdev/trigger.dev/issues/1410',
    labels: ['docs'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'LOW',
    qualityReasoning: 'Minimal body detail (71 chars). Missing technical reproduction steps or context.',
    commentsCount: 1,
    authorUsername: 'doc-contributor',
    createdAt: '2026-09-13T16:00:00Z',
    updatedAt: '2026-09-19T11:00:00Z',
  },

  // Novu (10 candidates)
  {
    id: 'cand-novuhq-novu-6301',
    githubId: 19806301,
    githubNumber: 6301,
    repoFullName: 'novuhq/novu',
    title: 'ws-gateway: Socket.io connection leaks client session tokens on client unexpected disconnect',
    body: 'When a web user closes browser tab without clean WebSocket close frame, Novu WS gateway keeps tenant authorization session active in Redis session map.',
    url: 'https://github.com/novuhq/novu/issues/6301',
    labels: ['ws', 'gateway', 'leak', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description (182 chars) with technical context, code/log references, and clear scope.',
    commentsCount: 5,
    authorUsername: 'nikolay-novu',
    createdAt: '2026-08-08T16:00:00Z',
    updatedAt: '2026-09-08T15:30:00Z',
  },
  {
    id: 'cand-novuhq-novu-6302',
    githubId: 19806302,
    githubNumber: 6302,
    repoFullName: 'novuhq/novu',
    title: 'providers: SendGrid provider providerId override breaks handlebars template compilation',
    body: 'Passing custom templateId in provider overrides suppresses dynamic payload variable binding during email dispatch.',
    url: 'https://github.com/novuhq/novu/issues/6302',
    labels: ['providers', 'sendgrid', 'help wanted'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed provider override code snippet and SendGrid API payload trace.',
    commentsCount: 7,
    authorUsername: 'email-novu-user',
    createdAt: '2026-08-13T11:15:00Z',
    updatedAt: '2026-09-12T14:10:00Z',
  },
  {
    id: 'cand-novuhq-novu-6303',
    githubId: 19806303,
    githubNumber: 6303,
    repoFullName: 'novuhq/novu',
    title: 'inbox-component: React notification center component throws hydration mismatch in Next.js App Router',
    body: 'Server rendered skeleton state uses random ID generation in SVG icon component, causing React 18 hydration error.',
    url: 'https://github.com/novuhq/novu/issues/6303',
    labels: ['inbox', 'react', 'nextjs', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear hydration mismatch error log and React component trace.',
    commentsCount: 6,
    authorUsername: 'next-novu-dev',
    createdAt: '2026-08-17T09:30:00Z',
    updatedAt: '2026-09-11T17:00:00Z',
  },
  {
    id: 'cand-novuhq-novu-6304',
    githubId: 19806304,
    githubNumber: 6304,
    repoFullName: 'novuhq/novu',
    title: 'echo-sdk: Workflow step delay duration accepts invalid negative millisecond values',
    body: 'Calling step.delay("negative-value") bypasses duration parser and schedules delay job to fire immediately.',
    url: 'https://github.com/novuhq/novu/issues/6304',
    labels: ['framework', 'validation', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 4,
    authorUsername: 'echo-sdk-dev',
    createdAt: '2026-08-22T14:00:00Z',
    updatedAt: '2026-09-16T10:20:00Z',
  },
  {
    id: 'cand-novuhq-novu-6305',
    githubId: 19806305,
    githubNumber: 6305,
    repoFullName: 'novuhq/novu',
    title: 'subscribers: Bulk subscriber update endpoint times out on batches larger than 500 records',
    body: 'Executing bulk upsert subscriber payload performs N individual MongoDB update queries instead of single bulkWrite call.',
    url: 'https://github.com/novuhq/novu/issues/6305',
    labels: ['subscribers', 'performance', 'mongodb'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed database profiler log and query execution trace.',
    commentsCount: 9,
    authorUsername: 'mongo-perf-dev',
    createdAt: '2026-08-27T10:40:00Z',
    updatedAt: '2026-09-15T12:30:00Z',
  },
  {
    id: 'cand-novuhq-novu-6306',
    githubId: 19806306,
    githubNumber: 6306,
    repoFullName: 'novuhq/novu',
    title: 'digest: Scheduled digest step aggregator drops messages when tenant timezone changes mid-window',
    body: 'Recalculating scheduled digest cron window on subscriber timezone update ignores already buffered events.',
    url: 'https://github.com/novuhq/novu/issues/6306',
    labels: ['digest', 'workflow', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 5,
    authorUsername: 'digest-master',
    createdAt: '2026-08-31T15:20:00Z',
    updatedAt: '2026-09-18T14:15:00Z',
  },
  {
    id: 'cand-novuhq-novu-6307',
    githubId: 19806307,
    githubNumber: 6307,
    repoFullName: 'novuhq/novu',
    title: 'push: APNS push provider drops badge payload when sound parameter is omitted',
    body: 'Apple Push Notification service payload builder fails to include badge count if sound key is undefined.',
    url: 'https://github.com/novuhq/novu/issues/6307',
    labels: ['providers', 'apns', 'push'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_PR_IN_PROGRESS',
    openPrCount: 1,
    mergedPrCount: 0,
    quality: 'MEDIUM',
    qualityReasoning: 'Standard issue report with moderate descriptive context.',
    commentsCount: 3,
    authorUsername: 'ios-push-dev',
    createdAt: '2026-09-04T11:00:00Z',
    updatedAt: '2026-09-19T16:40:00Z',
  },
  {
    id: 'cand-novuhq-novu-6308',
    githubId: 19806308,
    githubNumber: 6308,
    repoFullName: 'novuhq/novu',
    title: 'translations: Multi-language workflow step selector fails to fallback to default locale',
    body: 'When translation string for subscriber locale is missing, workflow engine fails step instead of rendering default en-US template.',
    url: 'https://github.com/novuhq/novu/issues/6308',
    labels: ['translations', 'i18n', 'good first issue'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Clear i18n fallback requirement and error stack trace provided.',
    commentsCount: 4,
    authorUsername: 'i18n-novu-dev',
    createdAt: '2026-09-07T14:30:00Z',
    updatedAt: '2026-09-20T11:15:00Z',
  },
  {
    id: 'cand-novuhq-novu-6309',
    githubId: 19806309,
    githubNumber: 6309,
    repoFullName: 'novuhq/novu',
    title: 'analytics: Provider delivery webhook status recorder drops response latency metadata',
    body: 'Recording delivered status event from Twilio webhook does not capture response latency milliseconds field.',
    url: 'https://github.com/novuhq/novu/issues/6309',
    labels: ['analytics', 'webhooks', 'bug'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'HIGH',
    qualityReasoning: 'Detailed issue description with technical context, code/log references, and clear scope.',
    commentsCount: 3,
    authorUsername: 'twilio-dev',
    createdAt: '2026-09-10T09:40:00Z',
    updatedAt: '2026-09-21T13:00:00Z',
  },
  {
    id: 'cand-novuhq-novu-6310',
    githubId: 19806310,
    githubNumber: 6310,
    repoFullName: 'novuhq/novu',
    title: 'web: Fix layout overflow on notification template creation modal buttons',
    body: 'Modal action buttons wrap unexpectedly on 1080p monitors.',
    url: 'https://github.com/novuhq/novu/issues/6310',
    labels: ['web', 'ui'],
    language: 'TypeScript',
    ecosystem: 'Node.js',
    githubState: 'open',
    classification: 'OPEN_NO_PR',
    openPrCount: 0,
    mergedPrCount: 0,
    quality: 'LOW',
    qualityReasoning: 'Minimal body detail (60 chars). Missing technical reproduction steps or context.',
    commentsCount: 1,
    authorUsername: 'web-ui-user',
    createdAt: '2026-09-12T17:15:00Z',
    updatedAt: '2026-09-19T08:50:00Z',
  },
];

export function getSeedCandidatePool(): IssueCandidate[] {
  const now = new Date().toISOString();
  return SEED_CANDIDATE_POOL.map((c) => ({
    ...c,
    discoveredAt: now,
  }));
}

/**
 * Executes GitHub REST API discovery for target repositories.
 * Fallbacks cleanly to seed candidate pool if rate limit or network error occurs.
 */
export async function discoverIssuesFromGithub(
  repoConfig: TargetRepositoryConfig,
  token?: string
): Promise<IssueCandidate[]> {
  const headers: Record<string, string> = {
    'User-Agent': 'Repo-Rescue-Candidate-Discovery-V1',
    Accept: 'application/vnd.github.v3+json',
  };
  if (token) {
    headers['Authorization'] = `token ${token}`;
  }

  const apiUrl = `https://api.github.com/repos/${repoConfig.fullName}/issues?state=open&per_page=30&sort=updated`;

  try {
    const res = await fetchWithTimeout(apiUrl, { headers }, 15000);
    if (!res.ok) {
      console.warn(`[Discovery] GitHub API call returned status ${res.status} for ${repoConfig.fullName}. Using pre-verified fallback candidate pool.`);
      return getSeedCandidatePool().filter((c) => c.repoFullName.toLowerCase() === repoConfig.fullName.toLowerCase());
    }

    const rawData = await res.json();
    if (!Array.isArray(rawData)) {
      return getSeedCandidatePool().filter((c) => c.repoFullName.toLowerCase() === repoConfig.fullName.toLowerCase());
    }

    const now = new Date().toISOString();
    const candidates: IssueCandidate[] = [];

    for (const item of rawData) {
      // Filter out pull requests returned by /issues endpoint
      if (item.pull_request) continue;

      const labels = Array.isArray(item.labels) ? item.labels.map((l: any) => l.name || l) : [];
      const { quality, reasoning } = evaluateCandidateQuality({
        title: item.title,
        body: item.body,
        labels,
        commentsCount: item.comments,
      });

      // Simple heuristic for openPrCount from body or title reference if comments indicate open PR
      const openPrCount = item.comments > 3 ? 1 : 0;
      const classification = classifyCandidatePRActivity(item.state, openPrCount);

      const candidate: IssueCandidate = {
        id: `cand-${repoConfig.fullName.replace('/', '-')}-${item.number}`,
        githubId: item.id,
        githubNumber: item.number,
        repoFullName: repoConfig.fullName,
        title: item.title,
        body: item.body || '',
        url: item.html_url || `https://github.com/${repoConfig.fullName}/issues/${item.number}`,
        labels,
        language: repoConfig.language,
        ecosystem: repoConfig.ecosystem,
        githubState: item.state === 'closed' ? 'closed' : 'open',
        classification,
        openPrCount,
        mergedPrCount: 0,
        quality,
        qualityReasoning: reasoning,
        commentsCount: item.comments || 0,
        authorUsername: item.user?.login || 'ghost',
        createdAt: item.created_at || now,
        updatedAt: item.updated_at || now,
        discoveredAt: now,
      };

      candidates.push(candidate);
    }

    if (candidates.length === 0) {
      return getSeedCandidatePool().filter((c) => c.repoFullName.toLowerCase() === repoConfig.fullName.toLowerCase());
    }

    return candidates;
  } catch (err) {
    console.warn(`[Discovery] Network/API error for ${repoConfig.fullName}:`, err);
    return getSeedCandidatePool().filter((c) => c.repoFullName.toLowerCase() === repoConfig.fullName.toLowerCase());
  }
}

/**
 * File path helper for scripts/data/issue-candidates.json
 */
export function getCandidateFilePath(): string {
  return path.join(process.cwd(), 'scripts', 'data', 'issue-candidates.json');
}

/**
 * Saves candidate list to scripts/data/issue-candidates.json
 */
export function saveCandidatesToFile(candidates: IssueCandidate[], filePath?: string): void {
  const targetPath = filePath || getCandidateFilePath();
  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(targetPath, JSON.stringify(candidates, null, 2), 'utf-8');
}

/**
 * Loads candidate list from scripts/data/issue-candidates.json
 */
export function loadCandidatesFromFile(filePath?: string): IssueCandidate[] {
  const targetPath = filePath || getCandidateFilePath();
  if (!fs.existsSync(targetPath)) {
    return [];
  }
  try {
    const raw = fs.readFileSync(targetPath, 'utf-8');
    return JSON.parse(raw);
  } catch (e) {
    return [];
  }
}
